version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: 21ee776de63c102c5ba98cb4e294b3d67c5130c3f18133e91e96a70fef1654d1
    docker:
      - image: circleci/ruby:2.6.6-stretch-node-browsers-legacy
    executor: ruby/default
    steps:
      - checkout
      - run: gem install bundler -v 1.17.3
      - restore_cache:
          keys:
            - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1-{{ arch }}-{{ .Branch }}
            - gem-cache-v1

      - run: bundle install --path vendor/bundle

      - save_cache:
          key: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
      - run: chmod +x ./cc-test-reporter
      - run: ./cc-test-reporter before-build
      - run: ruby -v
      - run: bundle exec rspec; ./cc-test-reporter format-coverage -t simplecov -o tmp/codeclimate.backend.json coverage/.resultset.json --exit-code $?
